mongo:
  image: mongo:3.0.4
  ports:
    - "27017:27017"
  command: --smallfiles --rest
rabbitmq:
  image: resilva87/docker-rabbitmq-stomp:latest
  ports:
    - "61613:61613"
    - "15672:15672"
  environment:
    - RABBITMQ_USER=root
    - RABBITMQ_PASS=123456
web:
  #image: esvit/paphos-dashboard
  build: .
  ports:
    - "8000:5000"
  links:
    - mongo
    - rabbitmq
  environment:
    - RABBITMQ_USER=root
    - RABBITMQ_PASS=123456
    - "DASHBOARD_URL=http://localhost:5000"
    - "DASHBOARD_API_URL=http://localhost:5000/api"
